### ISSUE TITLE
Make mlxtend available through conda-forge

### ISSUE THREAD

**Issue by eyadsibai** [rasbt/mlxtend#143]
```conda install -c rasbt mlxtend```
would install the old version of mlxtend. It would be nice to have the new version available through conda.

**Comment by rasbt** [comment]
Hi,

I've recently removed the `conda` note from the installation documentation, because I found the conda distribution for this particular package a little bit redundant (since it doesn't have any c-extensions or other things that are trickly to install.

As far as I know, there shouldn't be a difference between installing it via pip (wheels) or conda, and I thought it would just save extra hassle creating conda versions for new releases. If I am not wrong, installing a package via conda's pip will put it into the same environment path as installing it via conda!?

Also, instead of creating a separate channel, I think it's maybe better to use `conda-forge` since they have a nice set of recipes? I think getting mlxtend on conda-forge would be neat.

Would love to hear your opinion

**Comment by eyadsibai** [comment]
I agree with you about having mlxtend on conda-forge. In general I do prefer conda over pip for several reasons. Conda does give any conflicts or compatibility issues with other packages if there is any dependencies when you provide the full list of packages, which pip doesn't do. Other than that I have no problem in using pip :+1: 
I saw the .conda directory within your mlxtend repo, this is why I assumed that you support installing using conda.

**Comment by rasbt** [comment]
Sounds like a plan! I edited this issue to have this on the roadmap! Thanks for the suggestion!

**Comment by japborst** [comment]
I think this issue is fixed now: https://anaconda.org/conda-forge/mlxtend

**Comment by rasbt** [comment]
oh yes, thanks, forgot to close it.
