### ISSUE TITLE
Extend apriori function to also allow generation of rules

### ISSUE THREAD

**Issue by JoshuaGoerner** [rasbt/mlxtend#157]
Hey Sebastian,

I am currently working on the topic of association analysis and after unsuccessfully looking through sklearn I found your package mlxtend - including `apriori.py` .

Based on your current implementation I do not see an option to generate rules from the list of frequent itemsets - or do I miss some other features beside the [apriori.py](https://github.com/bbardakk/mlxtend/blob/master/mlxtend/association/apriori.py) implementation?

I am not sure to what extent you or other contributors are already working on that topic. Seeing the issue #65 I was wondering if you already have included the rule generation, since - if I remember correctly - the discussed LIFT metric is based on the _support & confidence of association rules_.

If there is nothing in place I would be more than happy to help you implementing this feature based on the algorithm in _Tan, Pang-Ning, Michael Steinbach, and Vipin Kumar. Introduction to Data Mining. Pearson New International Edition.  Harlow: Pearson Education Ltd., 2014. (pp. 349-352)_.

Best
Joshua

**Comment by rasbt** [comment]
Hi, Joshua

Coincidentally, I took Pang-Ning Tan's Data Mining class a few years ago and was faced with the same problem -- I didn't find a good python implementation for association rule mining. However, I found Christian Borgelt's tool helpful for some tasks back then if you are looking for a quick solution to analyze your data at hand http://www.borgelt.net/apriori.html

Intended to implement the association rule mining based on the apriori collection here, but I somehow never followed up on this but I'd be happy about a PR some time if you are interested in working on this.

The LIFT metric is currently implemented based on True Positives, TN, FN, and FP prediction labels, which is not as general as the apriori -> frequent itemset -> association rule process I'd say but more like a subset task for a specific rule. 

So, maybe a good strategy to start with would be to at a confidence score to the output table of the apriori function (http://rasbt.github.io/mlxtend/user_guide/association/apriori/), with an optional confidence threshold?

**Comment by JoshuaGoerner** [comment]
Hey Sebastian,

I was not aware of calculating the LIFT metric based on TP, TN, FN & FP. Interesting to hear that.

Let me start with your [contribution workflow](http://rasbt.github.io/mlxtend/contributing/) and see if I can provide a sufficient PR :)

**Comment by rasbt** [comment]
Yeah, if honestly find lift charts for classifiers a bit unintuitive...

It should be analogous to computing it as `supp(X U Y) / (supp(Y) * supp(X))`, though. I just remembered that it was even implemented using a support function: https://github.com/rasbt/mlxtend/pull/136

I am still wondering how we could make a good API for the frequent itemset generation and association rule generation ... 

I think of the apriori algorithm as sth more general (i.e., just a means for frequent itemset generation) and I would probably keep it as a separate function, since there may be other applications where someone is interested in frequent itemsets only ... Or someone may want to generate frequent itemsets for association rule generation using a different algorithm.

I am not sure how efficient that would be, but maybe it would be better to have a second function (`association_rules(...)`?) that generates the rules from the output of the apriori function. The current apriori function could be renamed to `apriori_itemsets(...)` then for clarity, whereas `association_rules` would take these itemsets  to output different rules with confidence and LIFT. What do you think?

**Comment by JoshuaGoerner** [comment]
That is exactly what I thought of. Keeping the steps **frequent itemset generation** and **rule generation** separated makes perfect sense in terms of flexibility and further scalability. 

To not get confused with the terminology and allow further integration of other algorithms, I would suggest the following structure:

## Types of classes used (a.k.a. interfaces)

> Frequent Itemset Genarator

Classes that take a one-hot-encoded pandas DataFrame and generate a pandas DataFrame of frequent itemsets - therefore implement the `generate_frequent_itemsets(df, minsup, ...)` method. 

> Association Rule Generator


Classes that take a pandas DataFrame of frequent itemsets and generate a pandas DataFrame of association rules - thefore implement the `generate_association_rules(df, minconf, ...)`<sup>[1] </sup> method.


## Module Organisation
    ├── ...                       <- other mlxtend modules
    └── frequent_patterns         <- rename "association" to "frequent_patterns" (optionally)
        ├── apriori.py            <- frequent itemset generator implemented
        ├── association_rules.py  <- association rule generator implemented
        └── fpgrowth.py           <- frequent itemset generator implemented

## Open Questions

- [ ] Attributes of the frequent itemsets DataFrame (is "length" of current [apriori.py](https://github.com/rasbt/mlxtend/blob/master/mlxtend/association/apriori.py) needed?)
- [ ] Attributes and column types of the association rules DataFrame <sup>[2] suggested structure</sup>



These would be my two cents for today :)
___
[1] method parameter potentially later change to `generate_association_rules(..., criterion={'minconf', 'lift', ...}, threshold, ...) `

[2]

| ID | condition | consequent | support | confidence |
|---|---|---|---|---|
|0|[Bread, Milk]|[Eggs]|0.5|0.9|
|1|[Diapers]|[Beer]|0.6|0.8|
|...|...|...|...|...|

**Comment by rasbt** [comment]
Thanks for these detailed thoughts!

Although renaming modules is always a bit annoying, I agree that `frequent_patterns` is a better module name in the long run (e.g., in case we'd add `fpgrowth` at some point). 

> Attributes of the frequent itemsets DataFrame (is "length" of current apriori.py needed?)

Not really, I found it convenient for looking at the results (`np.bincount(df['length'])`) and filtering the DataFrame (e.g., `df[df['length'] == 2]`). However, it's not really needed I, and it is just additional fluff. We could remove it but maybe mention it in the documentation example so that users can quickly generate it if needed (e.g., via `df['length'] = df['itemsets'].apply(lambda x: len(x))`).

> Attributes and column types of the association rules DataFrame

Looks good! I am not sure if you left it out for simplicity, but I would probably also suggest a Lift column and maybe a Conviction column (https://en.wikipedia.org/wiki/Association_rule_learning#Conviction) so that the output DataFrame is consistent across columns independent of the threshold/criterion.


> condition & consequent

Not sure if this helps the general user, but I think the term "antecedent" is the more common term used in the data mining contexts. Although, I like "condition" better.

> [1] method parameter potentially later change to generate_association_rules(..., criterion={'minconf', 'lift', ...}, threshold, ...)

Hm, I am a bit confused and was just looking at the top of your post again where you mentioned classes. Do you have a more OOP approach in mind for the implementations? Personally, I prefered having a "regular" Python function for e.g., the apriori implementation since I found that an OOP approach like 

    ap = Apriori(*params)
    ap.transform(df)

was a bit overkill. Maybe it could be useful in certain contexts though to have a more sklearn-like API; on the other hand, since it outputs a pretty sklearn-unusual DataFrame format, I didn't think that this could be useful. Any thoughts on this?

**Comment by JoshuaGoerner** [comment]
## Q&A
> Attributes of the frequent itemsets DataFrame (is "length" of current apriori.py needed?)

Agree to your proposal to drop it from the apriori function but mention it in the documentation. As I was just using the `apriori` function today I discovered, that the index of the returned dataframe is neither ordered, nor unique. [DataFrame.reset_index()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.reset_index.html) should solve the issue, e.g. `df = df.reset_index()`. Your decision to quick fix it. Otherwise I would also implement the change.

> ... also suggest a Lift column and maybe a Conviction column 

Also agree on that point. Calculating lift and conviction in addition to confidence is not a big deal. Do you have other metrics in mind to be implemented?

> the term "antecedent" is the more common

Yes, you are right. I also double-checked it and looked it up in _Tan, Steinbach, Kumar_ and they also refer to it as **antecedents** and **consequents**

> Maybe it could be useful in certain contexts though to have a more sklearn-like API; on the other hand, since it outputs a pretty sklearn-unusual DataFrame format, I didn't think that this could be useful. Any thoughts on this?

Well I have to admit that I am still in the sklearn way of thinking. Using a "regular" Python function would also do the job and might be a bit more lean and as you mentioned be less confusing, since sklearn would not produce pd.DataFrames.

## First implementation
You may have a look at my fork of mlxtend. Since this is just for first demonstration purposes [neither test, nor other of you styleguides ](https://rasbt.github.io/mlxtend/contributing/)are in place.

The `generate_rules()` method takes basically three arguments:

1. _dataframe_ containing the frequent itemsets
2. _metric_ to decide whether or not a rule is considered to be of interest
3. _minimal threshold_ that determines the value range of the metric for which you would consider a rule interesting

Based on those parameters candidates are generated from the frequent itemsets and evaluated.

A first description can be found in [association_rules.ipynb](https://github.com/JoshuaGoerner/mlxtend/blob/rule_generation/docs/sources/user_guide/association/association_rules.ipynb) here.

The source code for the rule generation can be found in [association_rules.py](https://github.com/JoshuaGoerner/mlxtend/blob/rule_generation/mlxtend/association/association_rules.py).


Feedback is highly appreciated! :)

**Comment by rasbt** [comment]
> Your decision to quick fix it. Otherwise I would also implement the change.

Good catch! I think we can fix it with the future implementation, because most people don't use the master-branch (instead of the latest pip version) anyway.

> Also agree on that point. Calculating lift and conviction in addition to confidence is not a big deal. Do you have other metrics in mind to be implemented?

To be honest, I am not that big into association rule mining and currently can't think of any additional metrics that could be useful at this point.

> Well I have to admit that I am still in the sklearn way of thinking. Using a "regular" Python function would also do the job and might be a bit more lean and as you mentioned be less confusing, since sklearn would not produce pd.DataFrames.

Let's go with functions, then :). This function could then still be used in future to make a sklearn-like estimator if there's a context where this could make sense. E.g., like sklearn's `minmax_scale` and `MinMaxScaler` etc.

> You may have a look at my fork of mlxtend. Since this is just for first demonstration purposes neither test, nor other of you styleguides are in place.

Maybe just open a PR if you don't mind (without worrying about the style guides etc for now). It would make it easier to see the actual diffs and additions, and it makes it easier to comment on particular parts of the code. Since GitHub has the convenient "squash and merge" feature now, don't worry about having to many commits that could clutter up the history, this would all get resolved in the end :)

**Comment by JoshuaGoerner** [comment]
Alright, as you suggested I opened a PR (without the testing, cosmetics, etc.).

Please note, that the imports inside the [association_rules.ipynb](https://github.com/JoshuaGoerner/mlxtend/blob/rule_generation/docs/sources/user_guide/association/association_rules.ipynb) are mocked since it should only demonstrate the inteded use of the `generate_rules()` method.
