### ISSUE TITLE
get meta-features from a fitted StackingClassifier?

### ISSUE THREAD

**Issue by SunilKalmady** [rasbt/mlxtend#169]
Thanks for great package!
How do I get meta-features from a fitted StackingClassifier?
I couldn't find any attribute/function to fetch the meta-features ie prediction classes or probabilities from each of the stacked classifiers.

**Comment by rasbt** [comment]
Hi, Sunil. I am glad to hear that the package is useful! Regarding the meta-features ... they are currently not stored as class attributes. The reason was maybe that I didn't think they would be useful and would just eat up memory if stored as attribute.

However, you should be able to generate this features by executing `stackingcv._predict_meta_features(X)` after fitting (where `stackingcv` is an instance of `StackingClassifier`)

**Comment by SunilKalmady** [comment]
@rasbt  Thanks a lot for your reply! This helps!

**Comment by rasbt** [comment]
glad to hear that this works as a workaround :)
