### ISSUE TITLE
Unit test failed in mlxtend/plotting

### ISSUE THREAD

**Issue by whalebot-helmsman** [rasbt/mlxtend#192]
[logs](https://gist.github.com/whalebot-helmsman/ec86777fedddfafc99ad06be2a74ab82)

**Comment by rasbt** [comment]
Unfortunately, the link points to a non-existing page (404 error). How did you run the unit tests and which ones failed?

**Comment by whalebot-helmsman** [comment]
Fixed

**Comment by rasbt** [comment]
Hm, I am getting the same error now. I think I excluded all the plotting functions from the continuous integration tests a while ago because it was hard to test plotting functions via unittests (https://github.com/rasbt/mlxtend/blob/master/ci/.travis_test.sh#L9). It would still be good to know what has changed that make this particular function fail, but for #191 I guess we can ignore it since the plotting unittest is a separate issue. So maybe just run the unittests via

    nosetests -s -v  --exclude-dir=mlxtend/plotting

**Comment by whalebot-helmsman** [comment]
yup, it deffinitly helps

``
----------------------------------------------------------------------
Ran 253 tests in 83.991s

OK

``

**Comment by soumyadsanyal** [comment]
@rasbt @whalebot-helmsman  I came across the same issue when I ran `nosetests ./mlxtend/plotting -sv`.

When running these tests for PR #190 , the problem seemed to be that the `desired1` and `desired2` arrays reported the errors in the exact reverse order to what was generated by the `plot_learning_curves` function (both before and after my changes to it in PR #190 ).

I've tentatively changed this behavior and 'fixed' the tests by reversing these arrays.

I'll leave it to @rasbt to confirm that this _is_ the correct fix.

**Comment by vicre** [comment]
@whalebot-helmsman  hi, how did you run the tests? 
env: Ubuntu +anaconda3 + python 3.6.0 +Pycharm 
I use Pycharm to run test but I got this :
/home/XXX/anaconda3/bin/python /home/wguo/app/ide/apps/PyCharm-P/ch-0/171.4249.47/helpers/pycharm/_jb_unittest_runner.py --target test_kernel_pca.test_default_components
Testing started at 10:55 PM ...
Launching unittests with arguments python -m unittest test_kernel_pca.test_default_components in /home/XXX/git/0ds/mlxtend/mlxtend/feature_extraction/tests
Traceback (most recent call last):
  File "/home/XXX/app/ide/apps/PyCharm-P/ch-0/171.4249.47/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=test_runner)
  File "/home/XXX/anaconda3/lib/python3.6/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/home/XXX/anaconda3/lib/python3.6/unittest/main.py", line 140, in parseArgs
    self.createTests()
  File "/home/XXX/anaconda3/lib/python3.6/unittest/main.py", line 147, in createTests
    self.module)
  File "/home/XXX/anaconda3/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/XXX/anaconda3/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/XXX/anaconda3/lib/python3.6/unittest/loader.py", line 211, in loadTestsFromName
    (obj, test))
TypeError: calling <function raises.<locals>.decorate.<locals>.newfunc at 0x7f88d1772ea0> returned None, not a test

Process finished with exit code 1
Empty test suite.
@rasbt   seems like the test writing style in mlxtend is quite different with doc mentioned in https://confluence.jetbrains.com/display/PYH/Creating+and+running+a+Python+unit+test#CreatingandrunningaPythonunittest-Creatingtest

**Comment by rasbt** [comment]
@vicre

The unittests are run via `nose`. I.e., by navigating into the mlxtend directory and executing `nosetests` (requires the `nose` package).

When I am looking at your log output, there's the line 

    Launching unittests with arguments python -m unittest test_kernel_pca.test_default_components in /home/XXX/git/0ds/mlxtend/mlxtend/feature_extraction/tests

I think that the `unittest` module is generally not compatible with nosetests as they are currently implemented.

I had some plans replacing `nose` by using the `unittest` module some time ago, since it's in the standardlib, which it's generally a nice thing. I use `unittest` in some other projects and don't have any issues with it (just happened that I started this project with using nose); however, I also thought that it might not be worth the effort porting the current tests to `unittest` since `nose` still seems to be quite popular (e.g., scikit-learn among others are using nose).  

That being said, I wouldn't have anything against porting the tests over to unittest, but I thought it might be too time-consuming.
