### ISSUE TITLE
How to build a Stacking model performing better than XGBoost?

### ISSUE THREAD

**Issue by ajing** [rasbt/mlxtend#210]
I found that  Extra Tree,  XGBoost, and LightGBM performing well for my problem. So, I was thinking whether I can combine those models and make a better one. However, after using StackingCVRegressor, the CV performance is even lower than using xgb_base alone. Is there any reason for that?

```
stack = StackingCVRegressor(regressors=(lgb, xgb_base, et),
                            meta_regressor=xgb, 
                            use_features_in_secondary=True)
```

**Comment by rasbt** [comment]
Not sure what the exact reason is in this case. Does it perform "much" worse? Could be due to multicollinearity or so (does setting `use_features_in_secondary=False` help?). 

I haven't used it with xgb, and can't tell you about performance, but I'd say that since XGB is already performing some sort of ensembling, it may be overkill to do further stacking of different ensemble methods? 

CCing @EikeDehling since he has done more experiments with the `StackingCVRegressor`.

**Comment by EikeDehling** [comment]
Hi Thx for the mention :)

What i have understood so far, is that stacking doesn't always help. There is different approaches to "ensembling", for example averaging predictions from multiple models, there is stacking and there is stacking with keeping original features, and more complex approaches also.

Sometimes one thing works, sometimes the other works. I suggest trying all above approaches out, and seeing what gives the best results, i don't have a good feeling for what works in what situation yet.  

I've also read and observed that using many different base-models in stacking can help. You could for example try putting a linear model, or an SVM or a neural network into the mix.

**Comment by ajing** [comment]
Thanks for the great suggestion! 

@rasbt Stacking is doing slightly worse than using XGBoost alone. One problem with my previous approach is that I fixed all hyperparameters for the base models, which may hurt the performance. 

@EikeDehling You are right, this can totally depend on the situation. I will try more approaches.
