### ISSUE TITLE
Adding additional Association Rule Learning Algorithms and adding new performance metrics to them

### ISSUE THREAD

**Issue by MichaelKheifetz** [rasbt/mlxtend#230]
Hi! I spoke to Sebastian about this and he recommended I start an issue here. I was wondering if anyone would be interested in adding other Association Rule Learning algorithms to the mlxtend package, particularly Eclat and FP Growth (I really like using Apriori)? Also, I was thinking it would be great if someone would like to add other measures of interestingness to Apriori as well as the newly setup algorithms, particularly I am thinking about Conviction and Leverage? Thank you!

**Comment by rasbt** [comment]
Thanks for the suggestions. All the features you listed definitely sound like useful additions to me.

- Conviction & Leverage:

I think those two can be easily added to the `association_rules` mining function in http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/ similar to `'confidence'` and `'lift'`. In addition to adding them to the table, they would then also become valid arguments for the `metric` function there. (A useful reference for Conviction can be found here: https://en.wikipedia.org/wiki/Association_rule_learning#Conviction)

- Eclat and FPGrowth

I am not an expert in association rule mining, and without having done any reading, do they offer any advantages over apriori? In any case, it would be nice to add them as alternatives to `apriori`, having a similar API and outputting a `frequent_patterns` table that can then be used by the `association_rules` function.

**Comment by MichaelKheifetz** [comment]
I am definitely not an expert in this either yet by any means but from my research, I am under the impression that the biggest gains in Eclat and FP-Growth is performance/speed rather then the result itself. I don't know if that is a 100% accurate statement but that is the main difference between Apriori, Eclat and FP-Growth that I have been able to locate when reading about them.

**Comment by rasbt** [comment]
Yeah, I think you are right! I did some reading and it seems like that they are just different in terms of their algorithmic approach and the difference is the performance on small/medium/big-sized datasets. While all "problems" could be solved with one of the three algorithms in general, it certainly wouldn't hurt to have different options implemented and they could then be specified via an additional parameter in the `association_rules` function. For example, 

    association_rules(..., algorithm='apriori')
    association_rules(..., algorithm='fp-growth`)
    ...

**Comment by MichaelKheifetz** [comment]
Yeah, that was my impression as well. I think it would be great if that would be added as well as the Conviction & Leverage calculations. Thank you very much for looking into this as well!

**Comment by rasbt** [comment]
I just added "leverage" as a metric. 
I was also looking at conviction, but revisiting the equation (https://en.wikipedia.org/wiki/Association_rule_learning#Conviction), I saw that this is a weird & tricky one as it is not fully defined. I.e., it has (1 - confidence) in the denominator, which may result in a division by zero, which is undefined. One option would be to assign float('inf') in this case as this would probably be a rather 'large' score. However, it would make comparisons and sorting quite hard if there are multiple 'inf's, and it would likely break the current code unless some custom modifications are being added.

To be honest, I think that a metric that is mathematically not fully defined is somewhat flawed and probably not that useful in practice, and I am a bit hesitant to add it to the code, but I am happy to hear your suggestions and ideas how to deal with this.

the issue with this is that it's a weird metric that is not fully defined. Ie

**Comment by MichaelKheifetz** [comment]
I just uninstalled version 0.7.0 and did a pip install my mlxtend-0.8.0 ran the code changing the metric to "leverage" and it is giving me: ValueError: Metric must be 'confidence' or 'lift', got 'leverage'. Do you know why that might be?

Hmm, regarding Conviction being undefined in the special case that confidence = 1, can we exclude it at all such points in the algorithm where that is the case? What is typically done in algorithms where there is such a scenario? I would imagine this has to be a common case in the implementation of many algorithms because you will run into it whenever you have a formula with a divisor being able to equal 0.

**Comment by rasbt** [comment]
> I just uninstalled version 0.7.0 and did a pip install my mlxtend-0.8.0 ran the code changing the metric to "leverage" and it is giving me: ValueError: Metric must be 'confidence' or 'lift', got 'leverage'. Do you know why that might be?

Yeah, I haven't made an official release, yet. Since this is a bit of work, it's usually only done if enough features have accumulated to warrant the extra effort :P. So in this case, the 'leverage' would only be available through the master branch on GitHub (in version mxtend 0.8.1dev). You can install it, for example, using

    pip install git+git://github.com/rasbt/mlxtend.git


The list of features is kept here:

https://github.com/rasbt/mlxtend/blob/master/docs/sources/CHANGELOG.md

> Hmm, regarding Conviction being undefined in the special case that confidence = 1, can we exclude it at all such points in the algorithm where that is the case? What is typically done in algorithms where there is such a scenario? I would imagine this has to be a common case in the implementation of many algorithms because you will run into it whenever you have a formula with a divisor being able to equal 0.

I wouldn't exclude the point as they would have a very "good" score (i.e., 100% confidence). 

I did a bit more reading, and it seems that the co-domain or range of conviction seems to be 'officially' defined as [0, inf). So I think that using 'inf' in cases of zero division may be what's expected. I have to see how to implement this cleanly to avoid annoying 'zero division' warnings in the code.

**Comment by rasbt** [comment]
I just added the conviction metric like mentioned above. For Eclat and FPGrowth, I opened a new issue (#248) to keep things organized :)

**Comment by MichaelKheifetz** [comment]
Thank you very much, I really appreciate your work on this! I just tried it and got it to work!

**Comment by nivcoh** [comment]
Hi,
I just upgraded to version 10.0 and for some reason I'm still receiving the following error:
"Metric must be 'confidence' or 'lift', got 'conviction'" while executing : 
"rules = association_rules(frequent_itemsets, metric="conviction", min_threshold=1.2)"

same issue with "leverage".

please advise.

Kind Regards,
Niv

**Comment by rasbt** [comment]
Hm, this is weird. Just to make sure that the upgrade was successful and that you don't have a second copy of mlxtend in your path that may get imported by accident, could you provide the output via 

```python
import mlxtend
print(mlxtend.__version__)
```

in the session where you are receiving the error you mentioned above?

**Comment by nivcoh** [comment]
Hi
I get 0.10.0... does it mean this is acutaly very old version 0.1 or it's 10 ?

**Comment by rasbt** [comment]
Sorry, you are right, for some reason, this isn't in the latest version, yet. Btw. it should read zero-point-ten-point zero.

I was planning to make a new release version soon, but for now, you could install the latest version from GitHub directly, e.g., via executing

pip install git+git://github.com/rasbt/mlxtend.git

**Comment by nivcoh** [comment]
Hi,
Thanks. I just installed 0.11.0.dev0 version. 

BTW, the OnehotTransactions() seemed to be changed and about to be replaced.  I'll suggest to update your documentation accordingly since they are a very good source to learn association rules with. 

Thanks for the quick help here, much appreciated.
Niv

**Comment by rasbt** [comment]
Hope it works now! Thanks for the note about the documentation. A bit about how I currently handle it: There are jupyter notebooks in https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/ that I keep up to date when changes are made to the package. However, the web documentation should reflect the documentation associated with the latest stable release -- so that user's are not mislead by new changes that are only available in the current GitHub repo but not in the released version. The change you mentioned is already incorporated in the Jupyter Notebook (at https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/frequent_patterns/association_rules.ipynb), and once I make the 0.11.0 version for the release, I will update the web documentation accordingly :)
