### ISSUE TITLE
"skip_if_stuck" attribute of SFS class

### ISSUE THREAD

**Issue by nd26** [rasbt/mlxtend#234]
I was under the impression that both SFFS and SBFS cannot get stuck. I've implemented this algorithm from the original paper some months ago and I just came across this implementation which I've immediately tested. If I am not mistaken, the only type of loop that can exist is by allowing the removal of a feature that was just added (and vica versa for SBFS) to get into a loop. Nevertheless, the original pseudo-code prevents that. So, how come the algorithm can get stuck?

**Comment by rasbt** [comment]
Hm, I think you are right, the "getting stuck in a loop" issue would only occur if a feature i is excluded, then included again, then excluded, then included again etc. I think the "checking" is due to the implementation details that an excluded feature can be considered for inclusion in the next round. I think this could/should be cleaned up in the code.

Btw. would you mind sharing the algorithm definition (original pseudo-code) you mentioned

**Comment by nd26** [comment]
Hey, it's from the original paper which can be found here (pages 1121 & 1122 if I am not mistaken): http://www.sciencedirect.com/science/article/pii/0167865594901279
Step 2 doesn't allow it to be excluded if it's the same one that was just added (hence why conditional exclusion). Moreover, Step 3 allows for the recursive removal of more features iff there are more than 2 features (talking about SFFS). I am not sure if you allow the recursive removal of features as during the execution (with verbose=2) the # of features never goes down but only stay the same or go up.

**Comment by nd26** [comment]
Any updates?

**Comment by rasbt** [comment]
Thanks for sharing the article, I think my implementation was based on 

Ferri, F., et al. "Comparative study of techniques for large-scale feature selection." Pattern Recognition in Practice IV (1994): 403-413.

(the algorithm is outlined/summarized in the mlxtend docs). 

The implementation in the article you highlighted makes sense though, i.e., the checking of newly included/excluded features in the conditional inclusion/exclusion. E.g.,

<img width="409" alt="screen shot 2017-09-05 at 11 55 32 pm" src="https://user-images.githubusercontent.com/5618407/30093807-de926fd6-9295-11e7-8e85-adc4a4f609c1.png">

Obviously, this way no loops can happen I guess. 

I haven't had a chance to read through the code in detail again, but it appears that I implemented this check (if you look for `fixed_feature` in the code). 

I am not sure why I was thinking that the algorithm could get stuck ...

**Comment by rasbt** [comment]
I was thinking a bit more about this ... Say we have the following scenario:

1. Original subset: {0, 1, 2, 3}
2. Backward step (eliminate feat 1): {0, 2, 3}
3. Cond. inclusion (do nothing): {0, 2, 3}
4. Backward step (eliminate feat 0): {2, 3}
5. Cond. inclusion (incl. feature 1): {1, 2, 3}
6. Backward step (eliminate feat 1): {2, 3}
7. Cond. inclusion (incl. feature 0): {0, 2, 3}
...

E.g. from step 4 to 5 you improve the performance by adding feature 1 back, which has been removed in an earlier step (step 2). Then, from step 5 to 6, since you still want to get down to a small feature subset (let's say k=2) so a feature gets removed again.

Now, if the algorithm is implemented like mentioned in the paper, i.e.,

![screen shot 2017-09-06 at 4 43 45 pm](https://user-images.githubusercontent.com/5618407/30135116-9d21d7a2-9327-11e7-9aa2-3c4a44cf60c7.png)

Then the scenario above wouldn't be an issue. However say you have sth like

1. Orig {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
2. Backward  {0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12}, removed 5
1. Inclusion {0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12}, nothing
1. Backward  {0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12), removed 2
1. Inclusion {0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12}, nothing
1. Backward  (0, 1, 4, 6, 7, 8, 9, 10, 11, 12), removed 3
1. Inclusion {0, 1, 4, 6, 7, 8, 9, 10, 11, 12}, nothing
1. Backward  (0, 1, 4, 7, 8, 9, 10, 11, 12), removed 6
1. Inclusion {0, 1, 4, 7, 8, 9, 10, 11, 12}, nothing
1. Backward  (0, 1, 4, 7, 8, 9, 10, 12), removed 11
1. Inclusion {0, 1, 4, 7, 8, 9, 10, 11, 12} include 11
1. Backward  (0, 1, 4, 7, 8, 9, 10, 12), removed 11
1. Inclusion {0, 1, 4, 7, 8, 9, 10, 11, 12} include 11
1. ....

In the paper, I find the highlighted passage a bit weird -- or maybe I simply misunderstand...

![screen shot 2017-09-06 at 5 22 20 pm](https://user-images.githubusercontent.com/5618407/30135191-f4601c72-9327-11e7-9d01-32afe171512b.png)

I read it as follows:

if the model performance upon including feature x_{k+1} is better than the model performance upon including any of the other features (for all elements in j=1, ..., k), then include feature x_{k+1} and go back to step 1. If this is strictly followed, I assume that this could lead to an include/exclude loop as illustrated above.

**Comment by nd26** [comment]
But it comes down to the same restriction; you cannot add/remove what you've just removed/added. 

Let's talk about SBFS for ease of explaining.

The only unconstrained operation you can have is Step 1, i.e. you can remove a feature from the current feature set. Now, the inclusion operation comes with a certain type of "memory" as in, it remembers the feature you've just removed. That's for both Step 2 and Step 3. 

I think what confused you is that he said X_{k+1} instead of X_{k-1} which in a sense shows an insertion but it's actually the removal, the element at that "time step" which was up to that point kept in memory reached the constraint and as such it will be removed. I find SFFS is much easier to understand (due to k+1 being intuitive) and plus, SBFS is just the mirror version of it.

Tell me if that makes sense.

**Comment by rasbt** [comment]
Thanks for the feedback. Yeah, let's stick with SBFS for now maybe. I remember that I read the x_{k+1} correctly but wrote it down incorrectly for SFFS for some reason; also, my second example was silly because I did some hasty copy and paste ... sorry about that!! What I meant to write for the lower half was:

Current subset {0, 1, 4, 6, 7, 8, 9, 10, 12}
Step1: Backw {0, 1, 4, 7, 8, 9, 10, 12} [eliminated 6]
Step2: Incl  {0, 1, 4, 7, 8, 9, 10, 11, 12} [included 11]

Step1: Backw {0, 1, 4, 7, 8, 9, 10, 12} [eliminated 11]
Step2: Incl {0, 1, 4, 6, 7, 8, 9, 10, 12} [included 6]

Step1: Backw  {0, 1, 4, 7, 8, 9, 10, 12} [eliminated 6]
Step2: Incl {0, 1, 4, 7, 8, 9, 10, 11, 12} [included 11]

I agree with you that the conditional step (step 2) should have a memory of step 1, and this is currently also implemented. So, in SFBS, something like

step1: inlude feature i
step2: exclude feature i
step 1: include feature i

should not happen. However, what's additionally needed is that step 1 has a memory of step 2, otherwise the loop above ([eliminated 6], [included 11] ...) could happen. 

In any case, this would be much more elegant than the current "skip_if_stuck" and is super easy to implement it (just made the mod in a branch). However, whether it's required, it might be that I am currently not seeing the forest for the trees ...

**Comment by nd26** [comment]
No worries :)!

We have a list L which contains say (features_list, metric) and say the index is the number of features within features_list.

Current subset {0, 1, 4, 6, 7, 8, 9, 10, 12} 
L[9] = ((0, 1, 4, 6, 7, 8, 9, 10, 12), L9_{metric})
Step1: Backw {0, 1, 4, 7, 8, 9, 10, 12} [eliminated 6]
L[8] = ((0, 1, 4, 7, 8, 9, 10, 12), L8_{metric})
Step2: Incl {0, 1, 4, 7, 8, 9, 10, 11, 12} [included 11]
Now, in order to add 11, then the metric of {0, 1, 4, 7, 8, 9, 10, 11, 12} must be > than the metric for (0, 1, 4, 6, 7, 8, 9, 10, 12). Hence, at this point we have L[8] and L[9] and we know that {0, 1, 4, 7, 8, 9, 10, 11, 12} is better than (0, 1, 4, 6, 7, 8, 9, 10, 12),.

Step1: Backw {0, 1, 4, 7, 8, 9, 10, 12} [eliminated 11]
For this to happen, we must assume that by removing any is at least as bad/good as removing 11 and it just so happens for 11 to be randomly selected. A metric is assigned to (0, 1, 4, 7, 8, 9, 10, 12). If this is better than what the metric we already have in L[8][1] then we substitute. Nevertheless, we have the same sequence of features stored and hence no substitution happens (not that it matters for what we are trying to address).

Step2: Incl {0, 1, 4, 6, 7, 8, 9, 10, 12} [included 6]
Now, here we know that the algorithm cannot include 6 as "the metric of {0, 1, 4, 7, 8, 9, 10, 11, 12} must be > than the metric for (0, 1, 4, 6, 7, 8, 9, 10, 12)" and hence, this inclusion will not happen due to:

![image](https://user-images.githubusercontent.com/7026980/30156140-83a7a964-93c7-11e7-8944-07709be68814.png)

Which is not satisfied and as such Step 2 does not happen. Note that, if 6 was the best candidate then no other attribute was any better and as such this step will inherently be a removal and not an inclusion.

I hope the explanation is clear!

The reason I brought this "issue" up was that I found the option weird and that it might have suggested that the underline implementation was wrong. Now, in what way, I don't know; it might have been that you didn't use a list with metrics, it might have been that you don't allow the recursive removal of features or you do up to a point, etc. Because, in order to have such an option, then you stop doing recursive removal if the loop happens, which shouldn't. However, forcing such a constraint may not allow the algorithm to find the more optimal sublist of the features.

**Comment by rasbt** [comment]
> Step2: Incl {0, 1, 4, 6, 7, 8, 9, 10, 12} [included 6]
Now, here we know that the algorithm cannot include 6 as "the metric of {0, 1, 4, 7, 8, 9, 10, 11, 12} must be > than the metric for (0, 1, 4, 6, 7, 8, 9, 10, 12)" and hence, this inclusion will not happen due to:

I was just about to ask why "{0, 1, 4, 7, 8, 9, 10, 11, 12}" here, but yeah, they I noticed why we were on different wavelengths ... When performing the conditional inclusion, I was only comparing the performance after conditional inclusion to the performance after the step 1 elimination in order to decide whether to perform the conditional step. Or in other words, I didn't check with the performance of the cached feature subsets of same size that may have been obtained in previous iterations. Doing that solves the issue of course. Thanks for bringing that up!

**Comment by nd26** [comment]
No worries! Let me know how the implementation goes :)

**Comment by rasbt** [comment]
I already went ahead and had made the modification before I sent my last comment -- thanks for the feedback, I think we are on the same page now and I guess I can merge that to master.

Like I mentioned, I didn't check against the "cached"/previously stored sublist (`self.subsets_[len_of_subset_after_step_2]`) of the same length but only compared the performance of the conditional step (`k_score_c`) to the performance of step 1 (`k_score`). So, it was a pretty easy modification:

![screen shot 2017-09-07 at 3 41 24 pm](https://user-images.githubusercontent.com/5618407/30181958-0fb962c4-93e3-11e7-8100-2388bf17f693.png)
