### ISSUE TITLE
SFFS & SFBS recursively conditionally removing/adding features

### ISSUE THREAD

**Issue by nd26** [rasbt/mlxtend#243]
Hey,

(Will talk about SFFS)

I went through the code and I think there is something missing.

![image](https://user-images.githubusercontent.com/7026980/30423124-96b46bb8-994a-11e7-83b1-2d313be07476.png)

So, basically, you are missing a while inside the while for Step 3. The algorithm should continue conditionally removing features until either you cannot (cause condition doesn't hold) or only 2 features are remaining.

**Comment by rasbt** [comment]
Again, thanks a lot for the feedback. Based on the resource you referenced (I think it's Pudil, P., Novovičová, J., & Kittler, J. (1994). "Floating search methods in feature selection." Pattern recognition letters 15.11 (1994): 1119-1125.), you are right that it differs: the current SFFS implementation only removes max. one feature during the conditional exclusion step.

The SFFS/SFBS implementation is based on a different description of the algorithm:

![screen shot 2017-09-14 at 3 41 27 pm](https://user-images.githubusercontent.com/5618407/30452417-a09914da-9963-11e7-80fc-3332fe6bdca3.png)

(Ferri, F., et al. (1994). "Comparative study of techniques for large-scale feature selection." Pattern Recognition in Practice IV : 403-413.)

I probably wouldn't want to modify the default behavior of the SFFS/SFBS as it  currently does match the description in the mlxtend docs and changing it would produce different results for many people who used it (bad for reproducibility). But we could add a new parameter to enable the behavior you described since it would potentially increase the number of subsets being sampled and therefore could improve the pred. performance. 

Not sure what a good name for such a parameter would be, maybe `continuation_of_conditional`?

**Comment by nd26** [comment]
Hey, no worries :)

The issue is that the paper I am referencing is the original paper and as such, having different implementation results in having a different algorithm (and thus should be renamed). What makes this feature selection powerful is mainly this "floating" characteristic. 

So, If I were you, I would probably have the parameter for the next version but eventually would just remove it. And don't feel bad for that; there isn't any optimal feature selection algorithm which isn't exhaustive. Only considering that most of the times the features added are equal in terms of information gain, it's natural to get different subsets of features each time (especially when you have hundreds of features). Blame those who once they do get the subset, they give too much credit to it :)

What about recursive_floating?

**Comment by rasbt** [comment]
Yeah, the version I implemented was based on my handwritten notes from a chalkboard lecture (from a statistical pattern rec class I took ~5 years ago); I think we had a reference paper back then but I can't find it anymore (it was benchmark paper comparing SF(F)S to genetic algorithms). 

`recursive_floating` Yeah, that sounds better :)

**Comment by nd26** [comment]
Hey, if you need help let me know. Also, based on a vague estimate, how long do you need to have this complete? Asking as I would want to test with your implementation as well before submitting a paper draft.

**Comment by rasbt** [comment]
I actually had it implemented for the forward version and it was sitting around for a bit. I just added the `recursive_floating` for SFBS also. Based on my debugger, I would say that it seems to work, the only thing is that I haven't found a good case where `recursive_floating=True/False` makes a different with regard to the selection (i.e., I don't have a good unit test case yet). 

I know the code is probably (overcomplicated) now .... Anyway, I would appreciate it if you could have a look and let me know what you think ;)

**Comment by nd26** [comment]
emailed you :)
