### ISSUE TITLE
The 'res' option for 'plot_decision_frontiers' is error-prone

### ISSUE THREAD

**Issue by arteymix** [rasbt/mlxtend#308]
I learned the hard way that `res` has to be adapted to the min/max range of the feature, otherwise you can end-up with massive meshgrid.

Why not using `np.linspace` instead and having a consistent range of points?

**Comment by rasbt** [comment]
That's a good point. Hm, I think the idea behind it was to have a constant resolution analogous to working with images (i.e., to have a certain pixel density given the dimensions of the plot rather than the range of features). 

I agree with your point though, and it can be quite "dangerous" (computational resources-wise) to run it on a dataset where you have a large min-max range. I think it would be worthwhile changing this to use linspace as you suggested. Preferably, we should find good default values though -- ideally such that the plots in the examples are unchanged.

Would you like to submit a PR? Otherwise, I am happy to put that on my todo list ;)

**Comment by arteymix** [comment]
Everything is in #309!
