### ISSUE TITLE
Add markersize parameter to plot_decision_regions

### ISSUE THREAD

**Issue by jrbourbeau** [rasbt/mlxtend#340]
I recently needed to change the scatter plot marker size in `plot_decision_regions` to make the markers easier to see in a presentation. A relatively easy fix was to use the matplotlib style context manager to temporarily change the plotting style. For example, 

```python 
with plt.style.context({'lines.markersize': 50}):
        plot_decision_regions(X, y, clf, colors='C0,C1,C2', markers='ooo' , ax=ax)
```

However, given that `plot_decision_regions` already has a `markers` and `colors` parameter for adjusting the marker style, I thought it would be natural to have a `markersize` parameter to more easily adjust the scatter plot marker size. 

@rasbt does adding a `markersize` parameter to `plot_decision_regions` sound reasonable? If so, I can submit a PR.

**Comment by rasbt** [comment]
That's a good point, right now, the function is indeed a bit limited when it comes to styling and customization. Instead of adding a single styling param like `markersize`, maybe we could go even a bit further an let users give "full control" over additional parameters for the the styling of the individual plots.  

So, right now, we have the following three plotting functions inside

1) `contourf`:
https://github.com/rasbt/mlxtend/blob/bad20c19e46c28084537d0cd8bbec53f1b7f5126/mlxtend/plotting/decision_regions.py#L207

2) `scatter` for the data points in general:
https://github.com/rasbt/mlxtend/blob/bad20c19e46c28084537d0cd8bbec53f1b7f5126/mlxtend/plotting/decision_regions.py#L233

3) `scatter` for circling test data points (via X_highlight)
https://github.com/rasbt/mlxtend/blob/bad20c19e46c28084537d0cd8bbec53f1b7f5126/mlxtend/plotting/decision_regions.py#L233

Maybe one idea would be to define 3 dictionaries (defaulting to None), `scatter_kwargs`, `scatter_highlight_kwargs`, and `contourf_kwargs`, which would accept any arguments that are supported via the respective functions in matplotlib.

E.g. for your scenario, this could be

    plot_decision_regions( ... , scatter_kwargs={'markersize':50})

and then inside `plot_decision_regions`:

    plt.scatter(..., **scatter_kwargs)

What do you think?

**Comment by jrbourbeau** [comment]
Good point, I like the dictionary idea! I guess adding specific parameters can be a slippery slope. For example, why not add a marker edge color parameter? Or an alpha parameter? Etc. 

Also, passing dictionaries with plotting specific parameters is done in `seaborn` for several plotting functions (e.g. https://seaborn.pydata.org/generated/seaborn.pairplot.html), so I think users may be familiar with this type of thing. 

Thanks for the feedback, I'll work on a PR

**Comment by rasbt** [comment]
Sounds good :). Thanks!  

It would involve some extra efforts, but all the existing, fixed parameters that are being used right now should then ideally also only be used if they are not otherwise assigned by the given kwargs dictionary. 

Implementation-wise we would set the kwargs dictionaries to `None`, then check whether the currently fixed parameters like `edgecolor` are being included as keys in the respective kwargs, and if not, they could be added to these dicts. 

This should include arguments that come from 
                       
```python
plot_decision_regions(...
    markers='s^oxv<>',
    colors='red,blue,limegreen,gray,cyan'):
```

though as they are a bit differently determined.
