### ISSUE TITLE
[JOSS] Link to User Guide from Examples section?

### ISSUE THREAD

**Issue by mlgill** [rasbt/mlxtend#364]
This is a suggestion, not a requirement. Mlxtend has a really nice User Guide, but it took me some time to  find it since I saw the shorter examples section first. Is it worth linking to the user guide from the examples section for those who want more information?

**Comment by rasbt** [comment]
That's a good idea!

 I think it would make most sense to include such a link at the end of the examples section in the docstrings. E.g., 

```
    ...
    Returns
    -------
    scores : array of float, shape=(len(list(n_splits)),)
        Array of scores of the estimator for each bootstrap
        replicate.

    Examples
    --------
    >>> from sklearn import datasets, linear_model
    >>> from mlxtend.evaluate import bootstrap_point632_score
    ...
    >>> print('95%% Confidence interval: [%.2f, %.2f]' % (lower, upper))
    95% Confidence interval: [0.90, 0.98]

    More examples can be found in the user guide at
    http://rasbt.github.io/mlxtend/user_guide/evaluate/bootstrap_point632_score/
```

In addition to having helpful links in the API docs, it will also be useful if people use the `help` function in Python (or `?` in IPython).

However, the `ipynb2markdown.py` helper script should then remove this text & link from the output so that it doesn't appear on the linked website itself saying "***more*** examples can be found at ...", which could lead to some confusion.

**Comment by rasbt** [comment]
Alright, I just added links to the user guides to all API docs. Thanks again for this useful suggestion!
