### ISSUE TITLE
Question: Impact of Refit (StackingCVClassifier)

### ISSUE THREAD

**Issue by AllardJM** [rasbt/mlxtend#367]
Is it correct that from a practical perspective, regardless of the value of 'refit' the models (level 1) are actually refit on the full training data set?

**Comment by rasbt** [comment]
Good question. To me, it would make sense because we usually assume that fitting a classifier on more data from the same distribution should only improve it, not making it worse. Also, since this happens after fitting the level-2 classifier, there shouldn't be an issue with regard to overfitting. 

I just double-checked the description page (http://rasbt.github.io/mlxtend/user_guide/classifier/StackingCVClassifier/), and it's also mentioned in the algorithm description from ref [1].

**Comment by AllardJM** [comment]
Sorry - so the answer is yes, that the models are always refit to the full training data?

**Comment by rasbt** [comment]
I think in practice, it would work either way. However, refitting the model to the full training data is probably the more common variant, and one might expect (given the usual assumptions) that it performs slightly better.

**Comment by AllardJM** [comment]
I was asking about the documentation: The wording lead me to believe that this refitting happened regardless of how this parameter was set, it was called 'refit' but seemed based on the description that the only impact was if the estimator was cloned or not - that refitting happened either way.

`Clones the classifiers for stacking classification if True (default) or else uses the original ones, which will be refitted on the dataset upon calling the fit method.`
