### ISSUE TITLE
Computing Association Rules if Consequents and/or Antecedents are Missing

### ISSUE THREAD

**Issue by pinedbean** [rasbt/mlxtend#390]
Hi, 

I'm new for this package, I'm encounter an error "KeyError: frozenset" which I'm not sure how to overcome it. 

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/9152586/40951338-a6b2845c-68a0-11e8-9665-876d9aadd649.png">

**Comment by rasbt** [comment]
Hi,

I haven't seen this error before. The error basically means that it can't find the entry in the `frequent_items_dict`. Hard to tell why this is happening.

If possible, 

- do you have a chance to run the code on Python 3.x to rule out some unicode formatting issue (maybe there were some special characters in the original file)
- do you get similar errors when you are using a different metric?

I realize that this may not be possible, but it would be ideal for debugging of you could share the input dataset you used to create the `frequent_itemsets` data frame (e.g., privately), so that I could run this through a debugger and inspect the error in more detail.

**Comment by rasbt** [comment]
PS: Could you let me know which mlxtend version you are using. E.g., via 

    >>> import mlxtend
    >>> print(mlxtend.__version__)

**Comment by jonathonrambo** [comment]
Also running into the same issue. I am using an output from a homegrown FP-Growth alg instead of the output from the apriori that's packaged in mlxtend but the formatting adheres to what's outlined in the documentation. Also no special characters in the source data, just item IDs and order IDs. Also concat'd a letter to the item IDs to ensure str type in the item lists. Was not successful though.

Currently on mlxtend v0.12.0 and Anaconda 3.6.1.

**Comment by rasbt** [comment]
I am happy to look into that. Is it somehow possible to share the dataset or an excerpt to reproduce the issue? This would help immensely with running a debugger finding out what's going in. If it's proprietary data, maybe it's somehow possible to replace the strings by some placeholders and scramble that a little bit?

**Comment by jonathonrambo** [comment]
Hey, Sebastian

Sure! Here's a sample of the FP data that's going in. I'll also take a look under the hood to see what might be going on.

from mlxtend.frequent_patterns import association_rules

dict = {'itemsets': [['177', '176'], ['177', '179'], ['176', '178'], ['176', '179'], ['93', '100'], ['177', '178'], ['177', '176', '178']],
        'support':[0.253623, 0.253623, 0.217391, 0.217391, 0.181159, 0.108696, 0.108696]}

association_rules(pd.DataFrame(dict), metric="confidence", min_threshold=0.1)


Thanks

Jon

**Comment by rasbt** [comment]
Thanks a lot! Just looking at the example you posted, I think I know what could be going on. I.e. if you have a frequent itemsets like ['177', '176'] with support 0.253623 as in your example, the support for ['177'] and ['176'] is unknown. The support of at least one of the two is 0.253623, but the support for the other item might be higher. 

In any case, I think it's probably looking up the support for one of the single itemsets and hence throwing the error.

**Comment by rasbt** [comment]
Hmn, as a simpler alternative (and as an opportunity to speed up the algorithm), a parameter "support_only" could be added as an argument to "metric". This would only compute the support column and set everything to NaN by default.

Then, in scenarios where the KeyError occurs, once could raise the KeyError with an informative error message suggesting that either consequent or antecedent data should be added or "support_only" should be used.

**Comment by jonathonrambo** [comment]
Realized why I was having issues with my own FP-Growth output, messed up in regression testing forgetting that I filtered out those single node elements and their supports while checking something else.

I agree. I think the combination of the two options is definitely the right way to go in the case that the FP data would come from data outside of the native mlxtend.apriori output and could be missing those elements. Alternatively we could also just default to the support_only in the cases where this issue exists and also provide the warning explaining the NaN results.
