### ISSUE TITLE
404 url for plotting learning curve in documentation

### ISSUE THREAD

**Issue by LiutongZhou** [rasbt/mlxtend#397]
The example url in the documentation for plotting learning curve returns 404 page

http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.plotting/#plot_learning_curves 

http://rasbt.github.io/mlxtend/user_guide/plotting/learning_curves/

**Comment by rasbt** [comment]
Thanks for the note! Should have been `plot_learning_curves` instead of `learning_curves` -- just fixed it. The error will still appear in the online documentation though until the next mlxtend version comes out, because the documentation is automatically generated from the docstrings in the code, which already have some changes for the upcoming release.
