### ISSUE TITLE
TransactionEncoder() is very very slow over dataframe from pandas.read_csv('file')

### ISSUE THREAD

**Issue by Nikronic** [rasbt/mlxtend#433]
When you use pandas.read_csv('file') to read tansactions, you will get 'nan' in your dataframe. So after transforming these dataframe to list of lists (input arg of apriori function), there are alot of 'nan' values.
![1](https://user-images.githubusercontent.com/32401852/45311881-d7081b80-b53f-11e8-8e1a-457bf8c48222.JPG)
<br>
`transactions = []
for i in range(0,len(dataset)):
    transactions.append(list(dataset.iloc[i,].values))`
result : 
![2](https://user-images.githubusercontent.com/32401852/45311991-264e4c00-b540-11e8-8efc-e9f937c7ba26.JPG)<br>
So the below line, never finish it's job: `te_ary = te.fit(transactions).transform(transactions)`<br>
Stuck place :<br> `for transaction in X:
            for item in transaction:
                unique_items.add(item)` in `fit()` function in `transactionencoder.py` file.

Best regards

**Comment by rasbt** [comment]
pandas DataFrames are more meant for array data, hence it's probably not ideal to use it on a CSV dataset with so many missing values. You could try using the csv reader in Python to speed things up.

However, once you have the data in a DataFrame and convert it to a list of lists, I would recommend getting rid of the "nan"'s, otherwise they are probably treated as a transaction as well.

To remove the nan's from the DataFrame and generate a list of lists, you could do the following:

```python
lst = []
for sublist in df.values.tolist():
    clean_sublist = [item for item in sublist if item is not pd.nan]
    lst.append(clean_sublist)
```

Hope that helps!

**Comment by Nikronic** [comment]
The problem was only because of `nan` values.
And in the code you provided, `pd.nan` should replace with `np.nan`. `pandas` does not have `nan` attirbute. It is `numpy` attribute.
` clean_sublist = [item for item in sublist if item is not **_pd.nan_**]`
Thank you so much.

**Comment by rasbt** [comment]
> And in the code you provided, pd.nan should replace with np.nan. pandas does not have nan attirbute. It is numpy attribute.

Oh yeah, good point! In case the `np.nan` doesn't capture the nans, you could also use sth like

    clean_sublist = [item for item in sublist if not isinstance(item, string)]
