### ISSUE TITLE
ColumnSelector has the bug to select columns

### ISSUE THREAD

**Issue by tetrar124** [rasbt/mlxtend#499]
Dear Developers,

In ColumnSelector.py, the parameter of cols was recommended with using tuple or list, 
which was written and used on API documents,  
> cols : array-like (default: None)' http://rasbt.github.io/mlxtend/user_guide/feature_selection/ColumnSelector/  

but in class ColumnSelector line 79 to 81 as 
 ```
if hasattr(X, 'loc'):   
  t = X.loc[:, self.cols].values
else:     
  t = X[:, self.cols] 
```
and it dosen't work.

'loc' is used with the index of pandas, and X[:, self.cols] doesn't work,
so I think it should be replaced as 'iloc' to the method on API document,
```
if hasattr(X, 'loc'):   
  t = X.iloc[:, self.cols].values
```
and use a list only, it works well (tuple didn't work).

Sincerely,

**Comment by rasbt** [comment]
Hi there,

I am not working with pandas DataFrames in the context of machine learning applications (I usually prefer numpy arrays for numerical reasons and out of habit) but I think we added the pandas DataFrame support because some users were aiming for selecting columns by name. I.e., like in the unit tests:

```python
def test_ColumnSelector_with_dataframe():
    boston = datasets.load_boston()
    df_in = pd.DataFrame(boston.data, columns=boston.feature_names)
    df_out = ColumnSelector(cols=('ZN', 'CRIM')).transform(df_in)
    assert df_out.shape == (506, 2)
```

Now, I guess there might be an issue where the input array is a DataFrame but a user doesn't specify columns? In that case, like you suggest, we might need to use iloc.

I see that  you opened a PR. Let me comment further there ...

**Comment by tetrar124** [comment]
Thank you for your reply. I have understood the reason for these specifications.

When I use a large dataset with pandas, it is difficult to write the names of columns,
so please add the new feature for pandas by the PR if possible.
https://github.com/rasbt/mlxtend/pull/500
