### ISSUE TITLE
Linear Regression Plotting not working

### ISSUE THREAD

**Issue by saj1919** [rasbt/mlxtend#5]
Hi, First of all ... awesome work man !! 
I am new to python and after moving from R on kaggle found link to 'mlxtend'.

Now my issue is following code not plotting anything. 

from mlxtend.regression import lin_regplot
import numpy as np

X = np.array([4, 8, 13, 26, 31, 10, 8, 30, 18, 12, 20, 5, 28, 18, 6, 31, 12, 12, 27, 11, 6, 14, 25, 7, 13,4, 15, 21, 15])
y = np.array([14, 24, 22, 59, 66, 25, 18, 60, 39, 32, 53, 18, 55, 41, 28, 61, 35, 36, 52, 23, 19, 25, 73, 16, 32, 14, 31, 43, 34])
intercept, slope, corr_coeff = lin_regplot(X[:,np.newaxis], y,)

Other codes like classifiers and 1d,2d, learning curve are working as mentioned on main page.
Can you help in this regard ? Did I miss something .. all codes given by you seems to be straight forward !!!

**Comment by rasbt** [comment]
Hi, Swapnil,

thanks for the note! I didn't put a `plt.show()` inside those function since I thought that it can be useful in certain cases... Anyway, I was probably using `%matplotlib` in an IPython notebook and forgot about adding a `plt.show` in the Readme. Or maybe I should add a default parameter `show=True` to the functions, this could be useful ... :)

I just gave it a quick try, you just need to add the 2 lines `import matplotlib.pyplot as plt` and `plt.show()` as shown below:


<pre>
import matplotlib.pyplot as plt
from mlxtend.regression import lin_regplot
import numpy as np

X = np.array([4, 8, 13, 26, 31, 10, 8, 30, 18, 12, 20, 5, 28, 18, 6, 31, 12, 12, 27, 11, 6, 14, 25, 7, 13,4, 15, 21, 15])
y = np.array([14, 24, 22, 59, 66, 25, 18, 60, 39, 32, 53, 18, 55, 41, 28, 61, 35, 36, 52, 23, 19, 25, 73, 16, 32, 14, 31, 43, 34])
intercept, slope, corr_coeff = lin_regplot(X[:,np.newaxis], y,)
plt.show()</pre>

![figure_1](https://cloud.githubusercontent.com/assets/5618407/7594160/b98c2d4c-f8ac-11e4-9722-b408a6a59e26.png)

**Comment by saj1919** [comment]
Cool. Done !
