### ISSUE TITLE
ExhaustiveFeatureSelector not printing any progress

### ISSUE THREAD

**Issue by cliffrunner** [rasbt/mlxtend#508]
I am using a 32 core machine for feature selection. It is a regression problem with about 2000 observations and 5-76 predictors. It has been running for about 2 hours and no progress has been printed. Is this normal? 

I used SFS before and didn't have issue.

Thanks a lot.

**Comment by rasbt** [comment]
Hm, not sure why it doesn't show the progress if you are running it on multiple machines. Have you set `verbose=1` or `verbose=2`?

**Comment by cliffrunner** [comment]
well I did not... but based on the API there is no verbose option

**Comment by rasbt** [comment]
Sorry, was confusing this with the SequentialFeatureSelector. We should add a verbose option for the exhaustive one as well then (however, there's a print_progress=True one that should work...).

Btw. if you are using the Exhaustive one, 76 features is quite a lot. E.g., if you are planning on selecting a 10-feature subset, that would be ~ 10^12 estimators to fit and would probably not finish in a lifetime.

**Comment by cliffrunner** [comment]
Thanks for the answer!
I think you meant to say 2^10? But I agree with you 70 features is impossible to do exhaustive selection. 
So here is a more fundamental question, when I use SFS to do either forward or backward search, if my k_feature is 10, does the algorithm guarantee that this feature combination is the one that would give me the best score among all k feature combinations?

**Comment by rasbt** [comment]
> I think you meant to say 2^10?

No, sorry, this was not a typo, I meant 10^12. Since there are there should be that many ways for combining 10 features out of 76 (as per binomial coefficient).

> So here is a more fundamental question, when I use SFS to do either forward or backward search, if my k_feature is 10, does the algorithm guarantee that this feature combination is the one that would give me the best score among all k feature combinations?

No, but it would finish in reasonable time and could get you close. It's impossible to guarantee the optimal solution without doing exhaustive search.

SFS usually will get you very close to optimal though :)

<img width="868" alt="screen shot 2019-02-14 at 10 41 00 pm" src="https://user-images.githubusercontent.com/5618407/52834898-ad808c80-30a9-11e9-9b30-7a6a4b262899.png">

**Comment by cliffrunner** [comment]
Oh I see. Sorry I misunderstood your commend. Thanks a lot for the detailed explanation!

**Comment by rasbt** [comment]
you are welcome! I guess this issue is resolved then :)
