### ISSUE TITLE
The same `random_state` param for all models in stacked_models

### ISSUE THREAD

**Issue by a-n-ermakov** [rasbt/mlxtend#514]
It would be convenient to set the same `random_state` parameter value for stacked models and metamodel in classes:
- StackingClassifier
- StackingCVClassifier
- StackingRegressor
- StackingCVRegressor
I suggest the following backward compatible changes in API:
- new constructor param `random_state=None` - for all models (if None - do not set `random_state` param of models)
- new constructor param `meta_random_state=None` - for meta models (if None, use `random_state` param)
I can take to work implementation of this issue

**Comment by rasbt** [comment]
Thanks for the suggestion and considering this. However, I am not sure that this is really necessary to have as separate parameter, because you can already set the random seed for the individual models within the models itself. Reason is why I am a bit hesitant is that there will be two ways to set a random seed then, which could be confusing in terms of what has priority if a user has both a random seed set for the model but has a different/no random seed in the stacking classes, which is maybe a bit against Python's motto "There should be one-- and preferably only one --obvious way to do it."

**Comment by a-n-ermakov** [comment]
Thanks for comments! Yeah, of course there is a way to set random state for models in current implementation. My proposal is motivated by the following observation - user usually sets (80/20) one random_seed for all models. I agree that this is not a critical improvement, but more for the user convenience. 
Speaking of priorities, stacked model is a classical composition (as a GoF pattern) - i think it has intuitive priority's understanding: param of composition has a higher priority than params of model and metamodel.

**Comment by rasbt** [comment]
I can totally understand your motivation behind that, and I agree that it could add some more convenience. However, I sometimes think that adding more bells and whistles (more options) can also complicate the use -- when people use their own random seeds, they might wonder where/how exactly the global random seed in the stacking class is applied exactly, and what it overrides and what not. So, I suggest sticking with having users define the random seed on the algorithm level. I think, this could then also avoid issues when people using some algorithms that don't have a random_state parameter (e.g., if the algorithm doesn't require one -- I guess KNN and decision trees would be typical examples -- or the random_state attribute is named random_seed for some reason)
