### ISSUE TITLE
Availability of FP Growth and Prefix Span Algorithm in this library

### ISSUE THREAD

**Issue by bnriiitb** [rasbt/mlxtend#525]
Could you please confirm the availability of FP Growth and Prefix Span Algorithm in this library. If not implemented, are there any plans to implement in the near future?

**Comment by rasbt** [comment]
> FP Growth and Prefix Span Algorithm 

They are currently not implemented. I remember that someone wanted to take a knack at it, but that's a long time ago and I don't think this is currently being worked on. 

> any plans to implement in the near future?

sorry, but I don't think it will happen in near future. Personally, that's not a priority for me since arpiori works fine for the use case I have/had. Doesn't mean I don't want to implement it one day ... but other things have higher priority for me currently
