### ISSUE TITLE
Ability to install mlxtend with conda

### ISSUE THREAD

**Issue by jakesherman** [rasbt/mlxtend#53]
Hi,

I really love this package and the documentation, it's been very helpful for a machine learning beginner like myself. I am wondering if you would consider putting this package onto the Anaconda Cloud so that it can be downloaded with conda in addition to pip, like so:

```bash
conda install mlxtend
```

The benefit of doing this is it would make things easier for Windows users who install MiniConda (vs. Anaconda, which comes with a bunch of scientific computing packages by default) because some of this pacakge's dependencies (scipy, numpy, matplotlib) can be difficult to install on Windows via pip. 

Personally I am fine using pip, but I often share the code I write on Ubuntu with co-workers who use Windows, and for them using conda makes their lives easier. 

This is a very minor issue, but I hope it will make access to this package easier. 

Thanks!

**Comment by rasbt** [comment]
That's a good point, thanks for the suggestion -- plus, I am a big fan of conda myself ;). I haven't bundled a package for conda, yet, but I did a quick search and found a short tutorial that looks helpful: http://conda.pydata.org/docs/build_tutorials/pkgs.html#convert-conda-package

Since you mention Windows ... I have many machines sitting here, but none of them runs Windows though. However, I guess they should have some machines in our CS department that I could use to create the conda package for Windows.

I'll definitely take a look at bundling mlxtend over the next couple of weeks, and if you have any suggestions or tips (specifically regarding Windows), please let me know!

**Comment by rasbt** [comment]
Alright! Finally got around creating the conda packages! You can install it via

```
conda install -c rasbt mlxtend
```

Thanks for the suggestion!

**Comment by jakesherman** [comment]
Thank you very much!

**Comment by gopi1410** [comment]
This doesn't have the 0.5 version though

**Comment by rasbt** [comment]
Yeah, I didn't continue making the conda binaries since I didn't see any advantage of it over pip wheels; I think it should do exactly the same thing for this particular library (pls correct me if I am wrong). Was planning to add it to conda-forge though (https://github.com/rasbt/mlxtend/issues/143). Haven't used conda-forge's recipes, yet and would have to dig into it; if you are familiar with it, a PR would be most welcome!

**Comment by JonathanJHull** [comment]
Just reporting that I tried to install mlxtend with conda, but was rejected because the mlxtend binary doesn't work with python 3.0

**Comment by rasbt** [comment]
Sorry for the trouble, I have to admit that I haven't updated the conda install for a while. I planned to setup a conda-forge recipe but haven't got around that, yet! I just posted an issue (#218) and would welcome a contribution, but I'd also be happy to finally get to it soon! So, right now, pip would be the only option

**Comment by JonathanJHull** [comment]
Hi Sebastian
Thanks for the quick response.  Pip ended working OK for me.  Thanks for
all your great work on this package!!!  It's fantastic.

Sorry, I'm not able to help.  Keep up the good work.

Best regards,
Jonathan

On Tue, Jul 18, 2017 at 8:44 PM, Sebastian Raschka <notifications@github.com

**Comment by rasbt** [comment]
Glad to hear it works via pip and that it's useful to you. I thought conda may be a bit overkill for the project, since the installation should be quite smooth via pip, but yeah, it's on the roadmap for the future ! :)
