### ISSUE TITLE
PCA Correlation circle

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Ferreira** [rasbt/mlxtend#543]
I would like to add a correlation circle graph for PCA, like the one in R's FactormineR.

![nba](https://user-images.githubusercontent.com/19335547/58408689-e1078580-80a0-11e9-950b-18f992265c25.png)

**Comment by rasbt** [comment]
This would be a great addition! It could be added to the mlxtend.plotting submodule.

**Comment by Gabriel-Azevedo-Ferreira** [comment]
Hello @rasbt ,
Thanks! I implemented it and made a pull request.
The pull request failed. Looking at the reasons I found the following:
   - Travis: `ERROR: Failure: ModuleNotFoundError (No module named 'adjustText')`
           - This package was not strictly necessary, it basically rearranges the text in the figure in order to avoid conflicts and overlaps. I can remove the use of it in a next pull request, but, if there is a way to keep it, I think it would be good. What do you suggest me to do? How can I make Travis "understand" that it should install "adjustText" for the test?
   - appveyor: It seems that the error was due to other tests, not related to my submission. Does this make sense? It seems the failed tests are in "mlxtend/regressor/tests" and  "mlxtend/classifier/tests". It seems that the tests in  "mlxtend/plotting/tests" were not ran.

**Comment by rasbt** [comment]
Thanks! 

> In order to keep it, I added a line on ci/.travis_install.sh: pip install adjustText.

this would not be enough, I think, because then later the conda-forge build will also have problems. In that case, we would also have to add it to the setup.py requirements then.

But regarding the adjustText package, it would be good to avoid additional installation requirements and dependencies (since we already have so many) if possible. In that case, it looks like AdjustText is just a 1-file library when I see that correctly? (https://github.com/Phlya/adjustText). We could simply add it to the mlxtend.externals subpackage since it's licensed under MIT license, which is compatible with mlxtend. I.e., similar to the `six` library (https://github.com/rasbt/mlxtend/blob/master/mlxtend/externals/six.py) with the license file on top.

Could you change that?

**Comment by rasbt** [comment]
Added via #544

**Comment by BrandonKMLee** [comment]
@rasbt thanks for including this

**Comment by BrandonKMLee** [comment]
@rasbt is it possible to put a scatter plot on top of the correlation circle for interpretability purposes?
