### ISSUE TITLE
mlxtend apriori Error

### ISSUE THREAD

**Issue by easonlv** [rasbt/mlxtend#592]
I meet an error "invalid syntax"  when running the apriori algorithm.
The code is blow:

```
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
```

  File " ~/anaconda/lib/python2.7/site-packages/mlxtend/frequent_patterns/apriori.py", line 191
    (iter_count, next_max_itemset), end="")
                                       ^
SyntaxError: invalid syntax

**Comment by rasbt** [comment]
The problem is probably that you are using Python 2.7. We stopped supporting and testing for Python 2.7 about half a year ago.

In that case, you would need to install a more current version of Python; I recommend version 3.7 against which everything is tested.

I am closing this now because this probably addresses the issue, but please let me know if you have any additional questions about that or installing Python 3.7; happy to help.
