### ISSUE TITLE
Is Python 3.5 supported?

### ISSUE THREAD

**Issue by ecederstrand** [rasbt/mlxtend#597]
https://github.com/rasbt/mlxtend/commit/d9b5c40ae57f0014afe479c48b1be65313527a39 introduced f-strings which are not supported in Python 3.5. setup.py advertizes support for both Python 2 and python 3.5.

Should I submit a fix for the f-strings, or is the setup.py too broad by mistake?

**Comment by rasbt** [comment]
Coincidentally, a student just came to me yesterday after class with exactly this problem --> mlxtend fails to import due to the f-strings in the heatmap func. 

I am actually in favor of embracing Python's new features and use f-strings. Most people use recent versions of Python -- in the case of the student, it turned out that he was mistakenly using an older version of Python that was on his system. Currently, also partly due to the already existing resource complexity, unit tests only run for Python 3.7.

I would be happy to hear your opinion though.


The setup.py file should be updated in any case!

**Comment by ecederstrand** [comment]
Thanks for the fix!

Previously, I erred on the side of only supporting the latest and greatest. We need to move forward, it' nice to work with modern features, extra work should be on the person working with legacy systems, etc.

After working with corporate systems for many years, I see how that doesn't fly, for many valid reasons. So now I try in my own projects to support the Python versions that are currently supported, i.e. 2.7, 3.5, 3.6 and 3.7.

The ideal solution is to have branches for each Python version so you are not constrained by the lowest version. But for 1-person projects, and most projects for that matter, the overhead is just too large.

In any case, I think packages should only advertise support for the Python versions that are actively tested. So I think your patch is the right way to go.

**Comment by rasbt** [comment]
Thanks for your feedback. I agree with you: in an ideal world, I would like to support more Python versions. But like you said, since this is more of a "hobby" project, maintaining just one current version is already a lot of effort :). 

Yeah, I back then, these versions were supported, but I dropped them one by one after some time when things required workaround for implementing certain things for both version (this was particularly true for Python 2.7). My bad was that I only updated the Readme with respect to the supported Python versions but forgot to update the setup.py file accordingly.
