### ISSUE TITLE
stacking estimators use cases

### ISSUE THREAD

**Issue by qiagu** [rasbt/mlxtend#601]
I have played a while using the estimators in the stacking family, like `StackingCVClassifier`, `StackingCVRegressor` and `StackingRegressor`, on my own datasets. I also did a lot of hyperparameter grid searches with simple estimators, like `XGBClassifier`, `RandomForestClassifier`, and so on. By far, stacking estimators hardly win vs. well-tuned simple estimators.  My ideas for further exploration are almost exhausted.

Could someone please give me some help or kindly provide  a few success cases of stacking estimators outperforming tuned simple estimators? I would be grateful for any assistance.

**Comment by rasbt** [comment]
Hm, the general stacking idea is a pretty old one. E.g., paper "Stacked Generalization" was from ~1992, which is even before random forests etc. It could very well be that XGBClassifiers, well tuned, would usually almost always be preferable -- I wouldn't call them "simple" though since they are ensemble methods themselves. My guess the original use case was for combining non-ensemble methods (like decision trees etc.).

In any case, I don't have any practical insights with regard to comparisons, but I do remember that (at least back in the day when Kaggle was relatively new) a lot of competitions were won by stacking multiple XGBoost classifiers etc. Wasn't the Netflix prize won by sth like this?

**Comment by qiagu** [comment]
I know little about the history of stacking method, nor the Netflix story.  Stacking multiple XGBoost classifiers sounds a brilliant call that I haven't tried yet. Thank you so much @rasbt
