### ISSUE TITLE
apriori.py error issue

### ISSUE THREAD

**Issue by ChrisWu108** [rasbt/mlxtend#635]
out = (np.sum(_x, axis=0) / _n_rows), will get wrong support result int/int

should be changed to:
out = (np.sum(_x, axis=0) / **float**(_n_rows))

**Comment by rasbt** [comment]
Thanks for the note. I don't think this would result in a wrong result though, because in Python 3, we have

```
>>> 1/2
0.5
```

etc. Would be an issue if someone would run this on Python 2.7.x but I am not sure if mlxtend even installs in Python 2.7. We have stopped testing for it about a year ago to simplify the code development.

**Comment by ChrisWu108** [comment]
yes, it's python2.7.
Thank you.

**Comment by rasbt** [comment]
Ok, so a fix wouldn't be necessary. I wouldn't recommend running the code in Python 2.7, this is not tested and there may be other places where similar issues occur.

**Comment by rasbt** [comment]
If you want to make the code compatible to Python 2.7, you are welcome to submit a PR though. However, we cannot recommend Python 2.7 for general use though because other functions in mlxtend may not work. So it would be only a small under the hood change if this would help you running this on your machine.

**Comment by ChrisWu108** [comment]
Cool. Thanks, will move to python3.

**Comment by rasbt** [comment]
Sounds good :)
