### ISSUE TITLE
plotvec2  is not defined error

### ISSUE THREAD

**Issue by navin7527** [rasbt/mlxtend#643]
Hi,
i am new to python  and i got this error notebook my code is below
import time 
import sys 
import numpy as np
import  matplotlib.pyplot as plt
%matplotlib inline
a=np.array([1,0])
b=np.array([01])
plotvec2(a,b)
print("this dot product is",np.dot(a,b))

then error comes like this
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-cf01ea606209> in <module>
      1 a=np.array([1,0])
      2 b=np.array([0,1])
----> 3 plotvec2([a,b])
      4 print("the dot product is",np.dot(a,b))

NameError: name 'plotvec2' is not defined
anyone can help me to solve this plz.

**Comment by rasbt** [comment]
Mlxtend doesn't have/use a function called `plotvec2`. You probably posted in the wrong forum.

**Comment by priyaajit** [comment]
just replace small p of Plotvec2 to capitals and it should work

**Comment by BishalGhimire** [comment]
Make sure you have defined the Plotvec2 function before using it.
For example, this would be a basic function:
def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

**Comment by varun2510** [comment]
@BishalGhimire , I am new to Numpy and plotting. Is it necessary to remember this whole thing by your heart so that you are able to define it whenever needed or its not about knowing it by heart? How do you guys define it ?

def Plotvec2(a,b):
ax = plt.axes()
ax.arrow(0, 0, a, head_width=0.05, color ='r', head_length=0.1)
plt.text((a + 0.1), 'a')
ax.arrow(0, 0, b, head_width=0.05, color ='b', head_length=0.1)
plt.text((b + 0.1), 'b')
plt.ylim(-2, 2)
plt.xlim(-2, 2)
