### ISSUE TITLE
Get scores by feature

### ISSUE THREAD

**Issue by shllgtca** [rasbt/mlxtend#662]
Hello,

I just started to use this package and I would like to know how to get the scores of the model by feature.

**Comment by rasbt** [comment]
Which model are you referring to, and what kind of scores are you after? In general, the following function will probably do what you want: http://rasbt.github.io/mlxtend/user_guide/evaluate/feature_importance_permutation/

**Comment by shllgtca** [comment]
I'm referring to the SequentialFeatureSelector. It sounds that there's just the general score of the model, and not the score for each feature.

**Comment by rasbt** [comment]
I see. So in the SFS, the importance or score is not computed on a per-feature basis. What's computed is the "score" for a subset of features. The philosophy behind SFS is that it does *not* assume independence between features. I.e,. there could be features that are only important in combination with others.

That being said, let's say you selected a feature subset, you can analyze the individual performance of each feature in that subset using e.g., http://rasbt.github.io/mlxtend/user_guide/evaluate/feature_importance_permutation/ as a follow-up

**Comment by shllgtca** [comment]
ok. I got it now. Thanks.

**Comment by rasbt** [comment]
glad that i could clarify. please let me know in case you have any other questions about this

**Comment by adam-ah** [comment]
@rasbt, this is a great explanation. May I propose adding this into the documentation as well?

Furthermore, the feature "importance" can be inferred by back-tracking how they were added one-by-one. Let's say the final list is [A,B,C], but you started with [C], then [B,C], then [A,B,C], then the order of importance is C,B,A, in decreasing order.

It is true that the exact importance of A can only be interpreted when B and C are present, but it does not mean that it was not added as last - starting with A would be a bad choice, hence there _**is**_ an order in the features - even if the exact weights cannot be computed.

Would it be better to retain this order in the lists, rather than returning them as arbitrarily sorted features (by column number, which is totally useless for sorting)?
