### ISSUE TITLE
Single Path in FPTree

### ISSUE THREAD

**Issue by shenxiangzhuang** [rasbt/mlxtend#706]
```python
def is_path(self):
    if len(self.root.children) > 1:
        return False
    for i in self.nodes:
        if len(self.nodes[i]) > 1 or len(self.nodes[i][0].children) > 1:
            return False
    return True
```
I think that these conditions are insufficient for us to judge if the FP-Tree contains a single path or not.
Does it just check the first two levels?

**Comment by harenbergsd** [comment]
Been a while since I looked at this, but I think it's OK.

Recall that in an FP-Tree, you have pointers between nodes representing the same item (or a list in this implementation). For instance, in this implementation, `self.nodes[i]` refers to the list of nodes representing item i in the tree.

If there are multiple nodes representing item i, `len(self.nodes[i]) > 1`, then the tree cannot be a single path and there must be multiple paths to the root. This simply follows from how the tree is constructed, you cannot build a path in the tree with multiple nodes representing the same item.

On the other hand, suppose that for all i `len(self.nodes[i]) <= 1`. Then, looping over all i and checking `self.nodes[i][0]` means we are visiting every node in the tree (because self.nodes[i] only has one item). If every node in the tree does not have more than one child node, then we know we have a path. Or, conversely, if there a node in the tree that has more than one child, we know the tree is not a single path; i.e., `len(self.nodes[i][0].children) > 1`.

**Comment by shenxiangzhuang** [comment]
Yes, your are right. I didn't found the path checking logic is related to the characteristics of FP-Tree.
Thank you for your patient and clear explanation.
