### ISSUE TITLE
Can be add or remove multiple features in SequentianFeatureSelector 

### ISSUE THREAD

**Issue by bifeng** [rasbt/mlxtend#716]
If there are thousands of features, then add/remove one features everytime is very consume. So is there any way to faster this approach in SequentianFeatureSelector ?

**Comment by rasbt** [comment]
> So is there any way to faster this approach in SequentianFeatureSelector ?

Here are a few tips:

- set `floating=False`
- if you want to keep a large number of features, do backward selection; if you want to keep a small number of features, do forward selection
- use multi-processing by setting `n_jobs` to a value larger than 1
- use fewer folds for cross-validation (like 3 instead of the 5 by default)
- use a smaller training dataset
- use a classifier that is faster to train

I hope that helps!
