### ISSUE TITLE
Can we have more parameters to pass for step wise feature selction

### ISSUE THREAD

**Issue by PriyatamNayak** [rasbt/mlxtend#742]
Do we have parameter in step wise like want to choose the best model on rmse or p value or t-statitics

want to have option for that?
do we have that?

**Comment by rasbt** [comment]
You can currently choose a scoring method compatible with scikit-learn.

```
scoring : str, callable, or None (default: None)

If None (default), uses 'accuracy' for sklearn classifiers and 'r2' for sklearn regressors. If str, uses a sklearn scoring metric string identifier, for example {accuracy, f1, precision, recall, roc_auc} for classifiers, {'mean_absolute_error', 'mean_squared_error'/'neg_mean_squared_error', 'median_absolute_error', 'r2'} for regressors. If a callable object or function is provided, it has to be conform with sklearn's signature scorer(estimator, X, y); see http://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.html for more information.
```

However, I think this would have limitations. The arguments for the underlying mechanism currently is `score_func(y, y_pred, ...)` and I assume you would need `score_func(y, y_pred_current_round, y_pred_previous_round)` to do anything with hypothesis testing, because you probably want to compare the current feature set to the feature set in the previous step.

Instead of exploiting the `scoring` method, it would probably be easier to add an entirely new parameter to the SequentialFeatureSelector for selection based on p-values. Like  `p_value_threshold` or something like that.

That being said. You can already 

> choose the best model on rmse

just not p value or t-statitics
