### ISSUE TITLE
Can't import SequentialFeatureSelector in Google colab

### ISSUE THREAD

**Issue by cequala** [rasbt/mlxtend#753]
```python
from mlxtend.feature_selection import SequentialFeatureSelector
```
Even if I reinstalled mlxtend using !pip and pip, I continually got the error message below.

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-90-03d2e0a7bacb> in <module>()
----> 1 from mlxtend.feature_selection import SequentialFeatureSelector

1 frames
/usr/local/lib/python3.6/dist-packages/mlxtend/feature_selection/sequential_feature_selector.py in <module>()
     21 from ..externals.name_estimators import _name_estimators
     22 from sklearn.model_selection import cross_val_score
---> 23 from sklearn.externals.joblib import Parallel, delayed
     24 
     25 

ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```

I'm using Google colab with GPU runtime.

#### Versions
MLxtend 0.14.0
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
Scikit-learn 0.23.2
NumPy 1.18.5
SciPy 1.4.1

**Comment by rasbt** [comment]
That's because you are using an old version for mlxtend I believe. Scikit-learn recently removed joblib from externals. Newer versions of mlxtend use the joblib library directly. E.g., see https://github.com/rasbt/mlxtend/blob/master/mlxtend/feature_selection/sequential_feature_selector.py#L23

You can fix your issue by ugrading mlxtend:

    !pip install mlxtend --upgrade

**Comment by cequala** [comment]
Oh, thanks! seems my mistake to put this as a bug.
