### ISSUE TITLE
Probably a good idea to move to py.test or plain unittest

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#92]
I've been a nose user for a long, long time, and yeah, I know it's been kind of "abandoned" for some time. However, I am also a big fan of the popular saying "_If it ain't broke, don't fix it_," since it can be a time sink in disfavor of more interesting, valuable, and useful improvements elsewhere. On the other hand, as long as this project is rather "small" and as long as a transition (from nose to py.test) is still "reasonably doable", I think it's better to switch over to py.test rather sooner than later ...

The reason why I bring this up now is that I just stumbled upon today's release of py.test 3.0 ver. And as a reflex, I checked the current status on [nose](http://nose.readthedocs.io/en/latest/) ... unfortunately, it still says:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

**Comment by MichalTHEDUDE** [comment]
Hi Sebastian! 
I can give it a try to work on this issue :).

Where should I start? Do you have some vision, plan? Or just replace all `tests` nose implementations with py.test? 

PS. I'm not badass Python Developer, but I think `py.test` is super easy and do it's job.

**Comment by rasbt** [comment]
Hi, Michal,
I think this is not a very pressing issue since `nosetest` works still fine; however, I heard good things about py.test, and since nosetests doesn't have a maintainer at the moment (or for several years), I thought it may be worth looking into it. Personally, I haven't really used py.test, the syntax looks a bit different but I heard that it is compatible to nosetest's syntax -- not sure if this is generally true though. Also, many people are praising it for its additional features & convenience functions, and I guess I'd be happy to use it at some point. But as I said, it's not urgent or so, however, if you like to work on it, I'd appreciate it :). If the compatibility statement is true, we simply need to update the continuous integration configuration files for travis and appveyor. Do you have experience with py.test and would you recommend it?

**Comment by MichalTHEDUDE** [comment]
Hmm, so maybe lets start with checking if `py.test` is working with existing `nosetest` code(I will check it and do additional google research).  If it is going to be fine we will just update .yml files (do the testing) and all the instructions, manuals etc.

Alas I'm not super skilled (yet) in Python Development (I'm still beginner). But I was helping in two projects (One startup and one for Mozilla) and both were using `py.test`. To be honest I've never heard of `nosetest`, but as I said I'm at the beginning of the Developer Journey :).

`py.test` works really good with both `numpy` and `pandas` (were using in startup project). But I don't have knowledge about any additional features. IMO `py.test` is way simpler that `unittest`, because you don't have to implement all those classes and so on. And I think that peoples are moving from `unittest` to `py.test`.

It is up to you :). I would love to learn both, `py.test` and `unittest`.
Maybe it will be good just to check if we can quickly move forward with `py.test`? What do you think?

**Comment by rasbt** [comment]
> Alas I'm not super skilled (yet) in Python Development (I'm still beginner). But I was helping in two projects (One startup and one for Mozilla) and both were using py.test. To be honest I've never heard of nosetest, but as I said I'm at the beginning of the Developer Journey :).

No worries! :), and I really appreciate your efforts! Nose is still pretty popular and most of the open-source libraries for scientific computing are still using it (prominent example would be scikit-learn). I am not sure if py.test would provide any advantage over nose at this point, since I haven't really used it, yet. However, I heard very good things about it, and since nose is not really maintained anymore, I thought that a switch may not be a bad idea at some point (before the code base grows larger and a transition becomes more painful :P). 

> py.test works really good with both numpy and pandas (were using in startup project). But I don't have knowledge about any additional features. IMO py.test is way simpler that unittest, because you don't have to implement all those classes and so on. And I think that peoples are moving from unittest to py.test.

Nice! That sounds very convincing :)

> Maybe it will be good just to check if we can quickly move forward with py.test? What do you think?

Sure, that would be a good thing to try. But yeah, you probably must be very busy as well so please only spend time on it if you have the time -- it's not a high-priority thing :)

**Comment by rasbt** [comment]
After giving it some more thought, I think it's probably not worth the effort moving to another unittest suite, because nose still works fine and does everything we want (in context of this project).
